name: Tests

on: [push, pull_request]

jobs:
  tests-linux:
    strategy:
      matrix:
        features:
          - feature: tokio
            name: tokio
          - feature: async-std
            name: asyncstd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps [Linux]
        run: sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        env:
          PROPTEST_CASES: 2500
          RUSTFLAGS: -D warnings -C target-feature=+avx,+avx2,+sse4.2
          RUST_BACKTRACE: 1
        run: cargo llvm-cov --workspace --lcov --output-path lcov.txt --features ${{ matrix.features.feature }} --no-default-features
      - uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.features.name }}
          files: ./lcov.txt